[package]
name = "bund"
version = "0.1.0"
edition = "2021"
description = "Interpreter and CLI for a Virtual Machine for BUND programming language"
license-file = "LICENSE"
repository = "https://github.com/vulogov/Bund"
categories = ["compilers"]
keywords = ["language", "stack", "concatenative", "lambda", "dynamic"]

[dependencies]
bund_language_parser = ">=0.*.*"
bundcore = ">=0.*.*"
clap = { version = "4.5.18", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
neofiglet = "0.1.1"
rust_dynamic = ">=0.*.*"
rust_multistackvm = ">=0.*.*"
